paths:
  archive: archive
  current: current
  processed: processed
  raw: raw

faq:
  current_file: faq_latest.txt
  archive_pattern: faq_%Y%m%d.txt
  preprocessor: FAQPreprocessor
  description: Frequently Asked Questions document

tender_notice:
  current_file: tender_notice_latest.txt
  archive_pattern: tender_notice_%Y%m%d.txt
  preprocessor: TenderNoticePreprocessor
  description: Current tender notice

terms_and_conditions:
  current_file: terms_latest.txt
  archive_pattern: terms_%Y%m%d.txt
  preprocessor: TenderTermsPreprocessor
  description: Terms and conditions document